version: '3.8'

services:
  # 1. The Database (Used only locally)
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Java Backend
  medipay-backend:
    build: ./medipay-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  # 3. Python Analytics
  python-analytics:
    build: ./medipay-analytics
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  # 4. Angular UI
  angular-ui:
    build: ./medipay-ui
    ports:
      - "80:80"
    depends_on:
      - medipay-backend
      - python-analytics
    
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616" # JMS Port
      - "8161:8161"   # Web Console (Admin UI)
      - "61613:61613" # STOMP Port (For Python to talk to JMS)  

volumes:
  postgres_data: